# Generated by Django 5.2.7 on 2025-10-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalMisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_misa', models.CharField(max_length=100)),
                ('hari', models.CharField(max_length=20)),
                ('waktu', models.TimeField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='jadwal/')),
            ],
        ),
    ]
