# Generated by Django 5.0.4 on 2025-10-15 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('ringkasan', models.TextField(help_text='Isi singkat berita (sekitar 2-3 kalimat).', max_length=300)),
                ('isi', models.TextField()),
                ('penulis', models.CharField(default='Admin', max_length=100)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
