# Generated by Django 5.0.4 on 2025-10-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utama', '0002_berita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='berita',
            options={},
        ),
        migrations.AlterField(
            model_name='berita',
            name='ringkasan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita', to='app_utama.kategori'),
        ),
    ]
